"""
tools/labeling/serve_images.py
==============================
Tiny CORS-enabled static file server for the bin images.

Why: Label Studio renders images on a cross-origin canvas (so it can zoom / draw
boxes), which requires the image server to send CORS headers. The public
aft-vbi-pds S3 bucket sends none, so S3 URLs fail to load in LS. This serves the
images we already have on disk WITH `Access-Control-Allow-Origin: *`, so LS loads
them fine — no Label Studio local-storage config or env vars needed.

Pair with tasks generated by:
    uv run python tools/labeling/make_label_studio_tasks.py --serve http

Usage (keep running in its own terminal while you label; Ctrl+C to stop):
    uv run python tools/labeling/serve_images.py
    uv run python tools/labeling/serve_images.py --port 9000
"""
from __future__ import annotations

import argparse
import os
import sys
from functools import partial
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

# code/data split aware (mirror the notebook bootstrap)
LOCAL_DATA = r"G:\My Drive\Interview Kickstart\Capstone Project\Amazon BinSense\data"
if not os.getenv("BINSENSE_DATA_DIR") and Path(LOCAL_DATA).exists():
    os.environ["BINSENSE_DATA_DIR"] = LOCAL_DATA
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from utils.env_utils import setup_env  # noqa: E402


class CORSHandler(SimpleHTTPRequestHandler):
    """Static handler that adds wide-open CORS so LS's canvas can load images."""

    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, OPTIONS")
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def do_OPTIONS(self):
        self.send_response(204)
        self.end_headers()

    def log_message(self, *args):
        pass  # quiet — one line per image request is noise


def main() -> None:
    ap = argparse.ArgumentParser(description="CORS static server for bin images.")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8081)
    ap.add_argument("--dir", type=Path, default=None,
                    help="images dir to serve (default: cfg.images_dir)")
    args = ap.parse_args()

    cfg = setup_env(verbose=False)
    root = args.dir or cfg.images_dir
    if not root.exists():
        print(f"Images dir not found: {root}")
        return

    handler = partial(CORSHandler, directory=str(root))
    srv = ThreadingHTTPServer((args.host, args.port), handler)
    print(f"Serving {root}")
    print(f"  http://{args.host}:{args.port}/<bin_id>.jpg   (CORS: *)")
    print("Generate matching tasks with: make_label_studio_tasks.py --serve http")
    print("Ctrl+C to stop.")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped.")


if __name__ == "__main__":
    main()
